---
name: Práctica Objetos y Mensajes
locale: es
type: practice
beta: false
teacher_info: "Ver primeros ejercicios de objetos y sin colecciones de acá: \n\nhttps://docs.google.com/document/d/1cCVgPPxfgoIj6OKuTXKB17S8PrGy77NbpbMTn33r1mo/edit"
language: wollok
id_format: '%05d'
order:
- 1
- 2
- 3
